import sqlite3

conn = sqlite3.connect('test.db')
conn.execute('''CREATE TABLE MOVIE
	(NAME CHAR(100) NOT NULL,
	DIRECTOR CHAR(50) NOT NULL,
	DB_MOVIE_ID CHAR(200) PRIMARY KEY NOT NULL);
	''')
conn.execute('''CREATE TABLE CELEBRITY
	(NAME CHAR(100) NOT NULL,
	DB_CELEBRITY_ID CHAR(200) PRIMARY KEY NOT NULL);
	''')

conn.execute('''CREATE TABLE MOVIE_ARTIST
	(MOVIE_ID CHAR(200),
	ARTIST_ID CHAR(200),
	FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(DB_MOVIE_ID),
	FOREIGN KEY (ARTIST_ID) REFERENCES MOVIE(DB_CELEBRITY_ID));
	''')
conn.commit

conn.close()